#
# Makefile for the kernel USB device drivers.
#

# Object files in subdirectories

obj-$(CONFIG_TINY4412_ADC)				+= tiny4412-adc/
obj-$(CONFIG_TINY4412_BACKLIGHT)			+= tiny4412-backlight/
obj-$(CONFIG_TINY4412_EEPROM)				+= tiny4412-eeprom/
obj-$(CONFIG_TINY4412_INTERRUPT)			+= tiny4412-interrupt/
obj-$(CONFIG_TINY4412_LCD)				+= tiny4412-lcd/
obj-$(CONFIG_TINY4412_LED)				+= tiny4412-led/
obj-$(CONFIG_TINY4412_PWM)				+= tiny4412-pwm/
obj-$(CONFIG_TINY4412_TOUCH)				+= tiny4412-touch/
obj-$(CONFIG_TINY4412_WDT)				+= tiny4412-wdt/
